name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main # Change this if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build static site using Docker
        run: make build

      - name: Copy README to build directory
        run: cp README.md ./build/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          external_repository: mamatnurahmat/mamatnurahmat.github.io
          publish_branch: master # or master, depending on your target repo's default branch
          publish_dir: ./build
          commit_message: "Auto-deploy: ${{ github.sha }}"
